gen2 profiles
arlonproj/arlon pull request #269
Opened 2022-10-18 03:44 UTC by bcle

2022-10-31 10:27 UTC, Rohitrajak1807 requested changes
@bcle I've made a pass through the code and left some comments.

2022-10-31 10:27 UTC, Rohitrajak1807 commented on pkg/ngprofile/detach.go
> +	}
If the `Lables == nil`, then can we conclude that the cluster doesn't have that profile added to it instead of initialising the Labels?

2022-10-31 10:27 UTC, Rohitrajak1807 commented on cmd/ngprofile/detach.go
> +	_ "embed"
Small doubt, why do we need the anonymous import for embed?

2022-11-30 02:39 UTC, bcle commented
Superseded by https://github.com/arlonproj/arlon/pull/335

2022-11-30 02:39 UTC, closed without merging