Added message for ArgoCD login in case of auth token expiry
arlonproj/arlon pull request #337
Opened 2022-12-01 08:28 UTC by ShaunakJoshi1407

Fixes: https://github.com/arlonproj/arlon/issues/81
As per the decision in this issue above, we have decided to inform the user to login into argocd incase the auth token has expired

2022-12-01 08:33 UTC, Rohitrajak1807 requested changes
I'd say to avoid duplication, add it as a persistent pre run hook to the root command.
Also, failure to create a client can have other reasons as well...

2022-12-01 17:50 UTC, cruizen commented on cmd/cluster/update.go
> +				return fmt.Errorf("failed to get cluster: %s", err)
```suggestion
				return fmt.Errorf("failed to update cluster: %s", err)
```

2022-12-02 08:50 UTC, Rohitrajak1807 approved these changes
seems fine... but an alternative would be to add this hook to the root command...
https://github.com/platform9/appctl/blob/master/cmd/root.go#L19
Perhaps we can refactor it later

Added the check in main.go

2022-12-02 09:35 UTC, ShaunakJoshi1407 commented
> seems fine... but an alternative would be to add this hook to the root command... https://github.com/platform9/appctl/blob/master/cmd/root.go#L19 Perhaps we can refactor it later

Added the check in main.go

2022-12-02 10:57 UTC, merged