Renaming base cluster to cluster manifest
arlonproj/arlon pull request #383
Opened 2022-12-19 19:27 UTC by jayanth-tjvrr

Fixes: #345 
This PR includes renaming of `base cluster` to `cluster manifest` everywhere in the docs of arlon and also clustertemplate alias has been added to basecluster command. So, now a user can a command as `arlon clustertemplate preparegit ....` and `arlon clustertemplate validategit ....`.

2022-12-19 19:54 UTC, bcle approved these changes
Some minor nits to address before merging.

2022-12-19 19:54 UTC, bcle commented on docs/clustertemplate.md
> +# Next-gen Cluster Provisioning using cluster template
Captalize and add 's': **Cluster Templates**

2022-12-19 19:54 UTC, bcle commented on docs/clustertemplate.md
> +clusters, the ones deployed from a cluster template are called next-gen clusters.
add "or gen2 clusters"

2022-12-20 12:10 UTC, cruizen commented on docs/gen2_overrides_proposal_3.md
> +`arlon cluster create <cluster-name> --repo-url <repo url where cluster template is present> --repo-path <repo path to the cluster template> --override <path to the patch file> --patch-repo-url <repo
```suggestion
`arlon cluster create <cluster-name> --repo-url <repo url where cluster template is present> --repo-path <repo path to the cluster template> --override <path to the patch file> --patch-repo-url <repo url where patch file should be stored> --patch-repo-path <repo path to store the patch file>` 
```

2022-12-20 12:12 UTC, cruizen commented on docs/clustertemplate.md
> +taken care of by the "prep" step on the cluster template*).
```suggestion
taken care of by the "prep" step on the *cluster template*).
```

2022-12-20 12:21 UTC, cruizen requested changes

2022-12-20 12:21 UTC, cruizen commented on docs/clustertemplate.md
>  This proposal describes a new way of provisioning workload clusters in Arlon.
```suggestion
This document describes a new way of provisioning workload clusters in Arlon.
```
This is no longer a proposal

2022-12-20 12:21 UTC, cruizen commented on docs/clustertemplate.md
> +To distinguish them from current generation, the ones deployed from a cluster template are called next-gen clusters or gen2 clusters.
```suggestion
To distinguish them from the older gen1 clusters, the ones deployed from a cluster template are called next-gen clusters or gen2 clusters.
```

2022-12-21 06:09 UTC, cruizen commented on docs/gen2_overrides_proposal_1.md
>  ```
```suggestion
```yaml
```

2022-12-21 06:10 UTC, cruizen commented on docs/gen2_overrides_proposal_1.md
>  # Gen2 Cluster Overrides - Proposal 1
```suggestion
# Gen2 Cluster Overrides - Proposal 1

```

2022-12-21 06:17 UTC, cruizen approved these changes
Approved. Take a look at minor markdown lint suggestions.

2022-12-21 07:40 UTC, merged