User docs for AppProfiles (a.k.a. gen2 profiles and apps)
arlonproj/arlon pull request #384
Opened 2022-12-19 20:43 UTC by bcle

2022-12-20 04:40 UTC, Rohitrajak1807 requested changes
Just one tiny change

2022-12-21 06:42 UTC, cruizen commented on docs/appprofiles.md
> +```
```suggestion
```shell
```

2022-12-21 06:42 UTC, cruizen commented on docs/appprofiles.md
> +```
```suggestion
```yaml
```

2022-12-21 06:43 UTC, cruizen commented on docs/appprofiles.md
> +```
```suggestion
```yaml
```

2022-12-21 06:44 UTC, cruizen commented on docs/appprofiles.md
> +```
```suggestion
```shell
```

2022-12-21 06:46 UTC, cruizen approved these changes
Approved. Made some minor formatting suggestions.

2022-12-21 16:29 UTC, merged